use ferrite_foundation::coordinate::BlockPos;

use crate::java_26_2::play::item::ItemStackTemplate;

pub const PARTICLE_TYPE_COUNT: i32 = 125;

#[derive(Debug, Clone, PartialEq)]
pub struct Particle {
    pub raw_type: i32,
    pub options: ParticleOptions,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ParticleOptions {
    Simple,
    BlockState(i32),
    Geyser {
        water_blocks: i32,
    },
    GeyserBase {
        water_blocks: i32,
        burst_impulse_base: f32,
    },
    Power(f32),
    Dust {
        color: i32,
        scale: f32,
    },
    DustTransition {
        from_color: i32,
        to_color: i32,
        scale: f32,
    },
    Spell {
        color: i32,
        power: f32,
    },
    Color(i32),
    Item(ItemStackTemplate),
    Vibration {
        destination: PositionSource,
        arrival_ticks: i32,
    },
    Trail {
        target: ParticleVector,
        color: i32,
        duration: i32,
    },
    Shriek(i32),
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ParticleVector {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub enum PositionSource {
    Block(BlockPos),
    Entity { entity_id: i32, y_offset: f32 },
}

#[must_use]
pub fn particle_identity(raw_type: i32) -> Option<&'static str> {
    PARTICLE_IDENTITIES.get(raw_type as usize).copied()
}

pub const PARTICLE_IDENTITIES: [&str; PARTICLE_TYPE_COUNT as usize] = [
    "minecraft:angry_villager",
    "minecraft:block",
    "minecraft:block_marker",
    "minecraft:bubble",
    "minecraft:sulfur_bubbles",
    "minecraft:noxious_gas",
    "minecraft:noxious_gas_cloud",
    "minecraft:geyser",
    "minecraft:geyser_base",
    "minecraft:geyser_poof",
    "minecraft:geyser_plume",
    "minecraft:cloud",
    "minecraft:copper_fire_flame",
    "minecraft:crit",
    "minecraft:damage_indicator",
    "minecraft:dragon_breath",
    "minecraft:dripping_lava",
    "minecraft:falling_lava",
    "minecraft:landing_lava",
    "minecraft:dripping_water",
    "minecraft:falling_water",
    "minecraft:dust",
    "minecraft:dust_color_transition",
    "minecraft:effect",
    "minecraft:elder_guardian",
    "minecraft:enchanted_hit",
    "minecraft:enchant",
    "minecraft:end_rod",
    "minecraft:entity_effect",
    "minecraft:explosion_emitter",
    "minecraft:explosion",
    "minecraft:gust",
    "minecraft:small_gust",
    "minecraft:gust_emitter_large",
    "minecraft:gust_emitter_small",
    "minecraft:sonic_boom",
    "minecraft:falling_dust",
    "minecraft:firework",
    "minecraft:fishing",
    "minecraft:flame",
    "minecraft:infested",
    "minecraft:cherry_leaves",
    "minecraft:pale_oak_leaves",
    "minecraft:tinted_leaves",
    "minecraft:sculk_soul",
    "minecraft:sculk_charge",
    "minecraft:sculk_charge_pop",
    "minecraft:soul_fire_flame",
    "minecraft:soul",
    "minecraft:flash",
    "minecraft:happy_villager",
    "minecraft:composter",
    "minecraft:heart",
    "minecraft:instant_effect",
    "minecraft:item",
    "minecraft:vibration",
    "minecraft:trail",
    "minecraft:pause_mob_growth",
    "minecraft:reset_mob_growth",
    "minecraft:item_slime",
    "minecraft:item_cobweb",
    "minecraft:item_snowball",
    "minecraft:large_smoke",
    "minecraft:lava",
    "minecraft:mycelium",
    "minecraft:note",
    "minecraft:poof",
    "minecraft:portal",
    "minecraft:rain",
    "minecraft:smoke",
    "minecraft:white_smoke",
    "minecraft:sneeze",
    "minecraft:spit",
    "minecraft:squid_ink",
    "minecraft:sweep_attack",
    "minecraft:totem_of_undying",
    "minecraft:underwater",
    "minecraft:splash",
    "minecraft:witch",
    "minecraft:bubble_pop",
    "minecraft:current_down",
    "minecraft:bubble_column_up",
    "minecraft:nautilus",
    "minecraft:dolphin",
    "minecraft:campfire_cosy_smoke",
    "minecraft:campfire_signal_smoke",
    "minecraft:dripping_honey",
    "minecraft:falling_honey",
    "minecraft:landing_honey",
    "minecraft:falling_nectar",
    "minecraft:falling_spore_blossom",
    "minecraft:ash",
    "minecraft:crimson_spore",
    "minecraft:warped_spore",
    "minecraft:spore_blossom_air",
    "minecraft:dripping_obsidian_tear",
    "minecraft:falling_obsidian_tear",
    "minecraft:landing_obsidian_tear",
    "minecraft:reverse_portal",
    "minecraft:white_ash",
    "minecraft:small_flame",
    "minecraft:snowflake",
    "minecraft:dripping_dripstone_lava",
    "minecraft:falling_dripstone_lava",
    "minecraft:dripping_dripstone_water",
    "minecraft:falling_dripstone_water",
    "minecraft:glow_squid_ink",
    "minecraft:glow",
    "minecraft:wax_on",
    "minecraft:wax_off",
    "minecraft:electric_spark",
    "minecraft:scrape",
    "minecraft:shriek",
    "minecraft:egg_crack",
    "minecraft:dust_plume",
    "minecraft:trial_spawner_detection",
    "minecraft:trial_spawner_detection_ominous",
    "minecraft:vault_connection",
    "minecraft:dust_pillar",
    "minecraft:ominous_spawning",
    "minecraft:raid_omen",
    "minecraft:trial_omen",
    "minecraft:block_crumble",
    "minecraft:firefly",
    "minecraft:sulfur_cube_goo",
];
