//! Locked construction profiles for all entity identities owned by ENT-001.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MobCategory {
    Ambient,
    Creature,
    Misc,
    Monster,
    UndergroundWaterCreature,
    WaterAmbient,
    WaterCreature,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Experience {
    Fixed(u8),
    Range { minimum: u8, maximum: u8 },
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EntityProfile {
    pub width: f64,
    pub height: f64,
    pub eye_height: f64,
    pub tracking_range: u8,
    pub update_interval: u8,
    pub category: MobCategory,
    pub available_in_peaceful: bool,
    pub max_health: f64,
    pub movement_speed: Option<f64>,
    pub attack_damage: Option<f64>,
    pub follow_range: Option<f64>,
    pub experience: Experience,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EntityKind {
    Bat,
    Blaze,
    Bogged,
    Breeze,
    CaveSpider,
    Cod,
    Dolphin,
    ElderGuardian,
    Endermite,
    Evoker,
    Ghast,
    Giant,
    GlowSquid,
    Guardian,
    Illusioner,
    IronGolem,
    MagmaCube,
    Parched,
    Phantom,
    PiglinBrute,
    Pillager,
    Pufferfish,
    Salmon,
    Shulker,
    Skeleton,
    Slime,
    SnowGolem,
    Spider,
    Squid,
    Stray,
    Tadpole,
    TropicalFish,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    WitherSkeleton,
}

impl EntityKind {
    pub const ALL: [Self; 37] = [
        Self::Bat,
        Self::Blaze,
        Self::Bogged,
        Self::Breeze,
        Self::CaveSpider,
        Self::Cod,
        Self::Dolphin,
        Self::ElderGuardian,
        Self::Endermite,
        Self::Evoker,
        Self::Ghast,
        Self::Giant,
        Self::GlowSquid,
        Self::Guardian,
        Self::Illusioner,
        Self::IronGolem,
        Self::MagmaCube,
        Self::Parched,
        Self::Phantom,
        Self::PiglinBrute,
        Self::Pillager,
        Self::Pufferfish,
        Self::Salmon,
        Self::Shulker,
        Self::Skeleton,
        Self::Slime,
        Self::SnowGolem,
        Self::Spider,
        Self::Squid,
        Self::Stray,
        Self::Tadpole,
        Self::TropicalFish,
        Self::Vex,
        Self::Villager,
        Self::Vindicator,
        Self::WanderingTrader,
        Self::WitherSkeleton,
    ];

    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Bat => "bat",
            Self::Blaze => "blaze",
            Self::Bogged => "bogged",
            Self::Breeze => "breeze",
            Self::CaveSpider => "cave_spider",
            Self::Cod => "cod",
            Self::Dolphin => "dolphin",
            Self::ElderGuardian => "elder_guardian",
            Self::Endermite => "endermite",
            Self::Evoker => "evoker",
            Self::Ghast => "ghast",
            Self::Giant => "giant",
            Self::GlowSquid => "glow_squid",
            Self::Guardian => "guardian",
            Self::Illusioner => "illusioner",
            Self::IronGolem => "iron_golem",
            Self::MagmaCube => "magma_cube",
            Self::Parched => "parched",
            Self::Phantom => "phantom",
            Self::PiglinBrute => "piglin_brute",
            Self::Pillager => "pillager",
            Self::Pufferfish => "pufferfish",
            Self::Salmon => "salmon",
            Self::Shulker => "shulker",
            Self::Skeleton => "skeleton",
            Self::Slime => "slime",
            Self::SnowGolem => "snow_golem",
            Self::Spider => "spider",
            Self::Squid => "squid",
            Self::Stray => "stray",
            Self::Tadpole => "tadpole",
            Self::TropicalFish => "tropical_fish",
            Self::Vex => "vex",
            Self::Villager => "villager",
            Self::Vindicator => "vindicator",
            Self::WanderingTrader => "wandering_trader",
            Self::WitherSkeleton => "wither_skeleton",
        }
    }

    #[must_use]
    pub fn from_path(path: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|kind| kind.path() == path)
    }

    #[must_use]
    pub const fn profile(self) -> EntityProfile {
        match self {
            Self::Bat => profile(
                (0.5, 0.9, 0.45),
                5,
                MobCategory::Ambient,
                true,
                (6.0, None, None, None),
                Experience::Fixed(0),
            ),
            Self::Blaze => profile(
                (0.6, 1.8, 1.53),
                8,
                MobCategory::Monster,
                false,
                (20.0, Some(0.23), Some(6.0), Some(48.0)),
                Experience::Fixed(10),
            ),
            Self::Bogged => skeleton_profile(16.0),
            Self::Breeze => profile(
                (0.6, 1.77, 1.3452),
                10,
                MobCategory::Monster,
                false,
                (30.0, Some(0.63), Some(3.0), Some(24.0)),
                Experience::Fixed(10),
            ),
            Self::CaveSpider => profile(
                (0.7, 0.5, 0.45),
                8,
                MobCategory::Monster,
                false,
                (12.0, Some(0.30000001192092896), Some(2.0), Some(16.0)),
                Experience::Fixed(5),
            ),
            Self::Cod => fish_profile((0.5, 0.3, 0.195)),
            Self::Dolphin => profile(
                (0.9, 0.6, 0.3),
                5,
                MobCategory::WaterCreature,
                true,
                (10.0, Some(1.2000000476837158), Some(3.0), Some(16.0)),
                Experience::Range {
                    minimum: 1,
                    maximum: 3,
                },
            ),
            Self::ElderGuardian => profile(
                (1.9975, 1.9975, 0.99875),
                10,
                MobCategory::Monster,
                false,
                (80.0, Some(0.30000001192092896), Some(8.0), Some(16.0)),
                Experience::Fixed(10),
            ),
            Self::Endermite => profile(
                (0.4, 0.3, 0.13),
                8,
                MobCategory::Monster,
                false,
                (8.0, Some(0.25), Some(2.0), Some(16.0)),
                Experience::Fixed(3),
            ),
            Self::Evoker => profile(
                (0.6, 1.95, 1.6575),
                8,
                MobCategory::Monster,
                false,
                (24.0, Some(0.5), Some(2.0), Some(12.0)),
                Experience::Fixed(10),
            ),
            Self::Ghast => profile(
                (4.0, 4.0, 2.6),
                10,
                MobCategory::Monster,
                false,
                (10.0, Some(0.06), None, Some(100.0)),
                Experience::Fixed(5),
            ),
            Self::Giant => profile(
                (3.6, 12.0, 10.44),
                10,
                MobCategory::Monster,
                false,
                (100.0, Some(0.5), Some(50.0), Some(16.0)),
                Experience::Fixed(5),
            ),
            Self::GlowSquid => profile(
                (0.8, 0.8, 0.4),
                10,
                MobCategory::UndergroundWaterCreature,
                true,
                (10.0, None, None, Some(16.0)),
                Experience::Range {
                    minimum: 1,
                    maximum: 3,
                },
            ),
            Self::Guardian => profile(
                (0.85, 0.85, 0.425),
                8,
                MobCategory::Monster,
                false,
                (30.0, Some(0.5), Some(6.0), Some(16.0)),
                Experience::Fixed(10),
            ),
            Self::Illusioner => profile(
                (0.6, 1.95, 1.6575),
                8,
                MobCategory::Monster,
                false,
                (32.0, Some(0.5), Some(2.0), Some(18.0)),
                Experience::Fixed(5),
            ),
            Self::IronGolem => profile(
                (1.4, 2.7, 2.295),
                10,
                MobCategory::Misc,
                true,
                (100.0, Some(0.25), Some(15.0), None),
                Experience::Fixed(0),
            ),
            Self::MagmaCube => cube_profile(8),
            Self::Parched => skeleton_profile(16.0),
            Self::Phantom => profile(
                (0.9, 0.5, 0.175),
                8,
                MobCategory::Monster,
                false,
                (20.0, None, Some(2.0), None),
                Experience::Fixed(5),
            ),
            Self::PiglinBrute => profile(
                (0.6, 1.95, 1.79),
                8,
                MobCategory::Monster,
                false,
                (50.0, Some(0.3499999940395355), Some(7.0), Some(12.0)),
                Experience::Fixed(20),
            ),
            Self::Pillager => profile(
                (0.6, 1.95, 1.6575),
                8,
                MobCategory::Monster,
                false,
                (24.0, Some(0.3499999940395355), Some(5.0), Some(32.0)),
                Experience::Fixed(5),
            ),
            Self::Pufferfish => fish_profile((0.7, 0.7, 0.455)),
            Self::Salmon => fish_profile((0.7, 0.4, 0.26)),
            Self::Shulker => profile(
                (1.0, 1.0, 0.5),
                10,
                MobCategory::Monster,
                true,
                (30.0, None, None, Some(16.0)),
                Experience::Fixed(5),
            ),
            Self::Skeleton | Self::Stray => skeleton_profile(20.0),
            Self::Slime => cube_profile(10),
            Self::SnowGolem => profile(
                (0.7, 1.9, 1.7),
                8,
                MobCategory::Misc,
                true,
                (4.0, Some(0.20000000298023224), None, Some(16.0)),
                Experience::Fixed(0),
            ),
            Self::Spider => profile(
                (1.4, 0.9, 0.65),
                8,
                MobCategory::Monster,
                false,
                (16.0, Some(0.30000001192092896), Some(2.0), Some(16.0)),
                Experience::Fixed(5),
            ),
            Self::Squid => profile(
                (0.8, 0.8, 0.4),
                8,
                MobCategory::WaterCreature,
                true,
                (10.0, None, None, Some(16.0)),
                Experience::Range {
                    minimum: 1,
                    maximum: 3,
                },
            ),
            Self::Tadpole => profile(
                (0.4, 0.3, 0.19500001),
                10,
                MobCategory::Creature,
                true,
                (6.0, Some(1.0), None, Some(16.0)),
                Experience::Fixed(0),
            ),
            Self::TropicalFish => fish_profile((0.5, 0.4, 0.26)),
            Self::Vex => profile(
                (0.4, 0.8, 0.51875),
                8,
                MobCategory::Monster,
                false,
                (14.0, Some(0.7), Some(4.0), Some(16.0)),
                Experience::Fixed(3),
            ),
            Self::Villager => profile(
                (0.6, 1.95, 1.62),
                10,
                MobCategory::Misc,
                true,
                (20.0, Some(0.5), None, Some(16.0)),
                Experience::Fixed(0),
            ),
            Self::Vindicator => profile(
                (0.6, 1.95, 1.6575),
                8,
                MobCategory::Monster,
                false,
                (24.0, Some(0.3499999940395355), Some(5.0), Some(12.0)),
                Experience::Fixed(5),
            ),
            Self::WanderingTrader => profile(
                (0.6, 1.95, 1.62),
                10,
                MobCategory::Creature,
                true,
                (20.0, Some(0.7), None, Some(16.0)),
                Experience::Fixed(0),
            ),
            Self::WitherSkeleton => profile(
                (0.7, 2.4, 2.1),
                8,
                MobCategory::Monster,
                false,
                (20.0, Some(0.25), Some(2.0), Some(16.0)),
                Experience::Fixed(5),
            ),
        }
    }
}

const fn profile(
    dimensions: (f64, f64, f64),
    tracking_range: u8,
    category: MobCategory,
    available_in_peaceful: bool,
    attributes: (f64, Option<f64>, Option<f64>, Option<f64>),
    experience: Experience,
) -> EntityProfile {
    EntityProfile {
        width: dimensions.0,
        height: dimensions.1,
        eye_height: dimensions.2,
        tracking_range,
        update_interval: 3,
        category,
        available_in_peaceful,
        max_health: attributes.0,
        movement_speed: attributes.1,
        attack_damage: attributes.2,
        follow_range: attributes.3,
        experience,
    }
}

const fn skeleton_profile(max_health: f64) -> EntityProfile {
    profile(
        (0.6, 1.99, 1.74),
        8,
        MobCategory::Monster,
        false,
        (max_health, Some(0.25), Some(2.0), Some(16.0)),
        Experience::Fixed(5),
    )
}

const fn fish_profile(dimensions: (f64, f64, f64)) -> EntityProfile {
    profile(
        dimensions,
        4,
        MobCategory::WaterAmbient,
        true,
        (3.0, Some(0.7), None, Some(16.0)),
        Experience::Range {
            minimum: 1,
            maximum: 3,
        },
    )
}

const fn cube_profile(tracking_range: u8) -> EntityProfile {
    profile(
        (0.52, 0.52, 0.325),
        tracking_range,
        MobCategory::Monster,
        false,
        (1.0, Some(0.3), Some(1.0), Some(16.0)),
        Experience::Fixed(1),
    )
}
