[package]
name = "ferrite-protocol"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ferrite-foundation.workspace = true
ferrite-registry.workspace = true
flate2.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[build-dependencies]
serde.workspace = true
sha1.workspace = true
toml.workspace = true
