[package]
name = "ferrite-cluster"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ctrlc.workspace = true
ferrite-region-runtime.workspace = true
ferrite-server-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
