[package]
name = "world-inspector"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
ferrite-persistence.workspace = true
ferrite-world.workspace = true
serde_json.workspace = true

[dev-dependencies]
ferrite-foundation.workspace = true
