[package]
name = "ferrite-tooling"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "ferrite-tooling"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile = "3"
